<?php
/**
 * RIVROSS Corporate theme foundation.
 *
 * @package Rivross_Corporate
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'RIVROSS_THEME_VERSION', '1.0.27' );

require_once get_template_directory() . '/inc/partner-logos.php';
require_once get_template_directory() . '/inc/customizer.php';
require_once get_template_directory() . '/inc/leadership.php';
require_once get_template_directory() . '/inc/hero-slides.php';
require_once get_template_directory() . '/inc/events.php';
require_once get_template_directory() . '/inc/news-single.php';
require_once get_template_directory() . '/inc/properties.php';
require_once get_template_directory() . '/inc/projects.php';
require_once get_template_directory() . '/inc/travel.php';
require_once get_template_directory() . '/inc/tea.php';
require_once get_template_directory() . '/inc/careers.php';
require_once get_template_directory() . '/inc/newsletter.php';
require_once get_template_directory() . '/inc/legal.php';
require_once get_template_directory() . '/inc/maintenance.php';
require_once get_template_directory() . '/inc/seo.php';
require_once get_template_directory() . '/inc/site-health.php';

/**
 * Sanitize a gallery field while keeping the editor-friendly one-URL-per-line
 * format used by the project and property editors.
 *
 * @param mixed $value Raw gallery value.
 * @return string
 */
function rivross_sanitize_gallery_urls( $value ) {
	$lines = preg_split( '/\r\n|\r|\n/', (string) $value );
	$urls  = array();
	foreach ( $lines as $line ) {
		$url = esc_url_raw( trim( $line ) );
		if ( '' !== $url && preg_match( '#^(?:https?:)?//#i', $url ) ) {
			$urls[] = $url;
		}
	}
	return implode( "\n", array_values( array_unique( $urls ) ) );
}

/**
 * Keep date fields in the ISO format used by native date inputs and queries.
 *
 * @param mixed $value Raw date value.
 * @return string
 */
function rivross_sanitize_date_value( $value ) {
	$value = sanitize_text_field( (string) $value );
	if ( ! preg_match( '/^\d{4}-\d{2}-\d{2}$/', $value ) ) {
		return '';
	}
	$parts = array_map( 'intval', explode( '-', $value ) );
	return checkdate( $parts[1], $parts[2], $parts[0] ) ? $value : '';
}

function rivross_setup() {
	/*
	 * Keep the theme's own strings ready for WordPress language packs and
	 * multilingual plugins. The customizer and page templates use the same
	 * text domain, so this also gives TranslatePress/WPML/Polylang a stable
	 * source for the theme UI strings.
	 */
	load_theme_textdomain( 'rivross-corporate', get_template_directory() . '/languages' );

	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'align-wide' );
	add_theme_support( 'custom-logo', array(
		'height'      => 80,
		'width'       => 260,
		'flex-height' => true,
		'flex-width'  => true,
	) );
	add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );
	add_theme_support( 'editor-styles' );

	register_nav_menus( array(
		'primary' => __( 'Primary Menu', 'rivross-corporate' ),
		'footer'  => __( 'Footer Menu', 'rivross-corporate' ),
	) );
}
add_action( 'after_setup_theme', 'rivross_setup' );

/**
 * Return the supplied primary Rivross mark for the public brand surfaces.
 *
 * The logo is intentionally theme-owned instead of tied to the previous
 * Customizer attachment, so the supplied mark remains stable after a content
 * import or Customizer reset.
 *
 * @return string
 */
function rivross_brand_logo_markup() {
	$url = get_template_directory_uri() . '/assets/images/brand/rivross-main-logo-transparent.png';
	$alt = get_bloginfo( 'name' ) . ' logo';

	return '<a class="custom-logo-link" href="' . esc_url( home_url( '/' ) ) . '" rel="home" aria-label="' . esc_attr( $alt ) . '">' .
		'<img class="custom-logo rivross-brand-logo" src="' . esc_url( $url ) . '" width="500" height="500" alt="' . esc_attr( $alt ) . '" decoding="async" fetchpriority="high" />' .
		'</a>';
}

/**
 * Establish the two external font connections before the stylesheet request.
 * This shortens the connection setup time without changing the font stack.
 *
 * @param array  $urls          Existing resource hints.
 * @param string $relation_type Hint relation being rendered.
 * @return array
 */
function rivross_resource_hints( $urls, $relation_type ) {
	if ( 'preconnect' !== $relation_type ) {
		return $urls;
	}

	$urls[] = 'https://fonts.googleapis.com';
	$urls[] = array(
		'href'        => 'https://fonts.gstatic.com',
		'crossorigin' => 'anonymous',
	);

	return $urls;
}
add_filter( 'wp_resource_hints', 'rivross_resource_hints', 10, 2 );

/**
 * Add safe browser hints to images generated by WordPress.
 *
 * Theme templates can still opt a critical image out of lazy loading with an
 * explicit loading attribute. This filter only fills in missing attributes,
 * so it remains friendly to optimization and image CDN plugins.
 *
 * @param array        $attr       Image attributes.
 * @param WP_Post|null $attachment Attachment post.
 * @param string|array $size       Requested image size.
 * @return array
 */
function rivross_image_performance_attributes( $attr, $attachment, $size ) {
	if ( ! array_key_exists( 'decoding', $attr ) || '' === $attr['decoding'] ) {
		$attr['decoding'] = 'async';
	}
	if ( ! array_key_exists( 'loading', $attr ) || '' === $attr['loading'] ) {
		$attr['loading'] = 'lazy';
	}
	return $attr;
}
add_filter( 'wp_get_attachment_image_attributes', 'rivross_image_performance_attributes', 10, 3 );

/**
 * Load the shared Media Library picker on every RIVROSS content editor that
 * exposes a custom image or gallery field. The picker also includes the
 * normal WordPress upload flow, so editors never need to paste image URLs.
 */
function rivross_cpt_media_admin_assets( $hook ) {
	if ( ! in_array( $hook, array( 'post.php', 'post-new.php' ), true ) ) {
		return;
	}
	$screen = get_current_screen();
	$post_types = array( 'rivross_hero_slide', 'rivross_property', 'rivross_project', 'rivross_event', 'rivross_job', 'rivross_leader' );
	if ( ! $screen || ! in_array( $screen->post_type, $post_types, true ) ) {
		return;
	}
	wp_enqueue_media();
	$script = get_template_directory() . '/assets/js/cpt-media-picker.js';
	wp_enqueue_script(
		'rivross-cpt-media-picker',
		get_template_directory_uri() . '/assets/js/cpt-media-picker.js',
		array( 'jquery' ),
		file_exists( $script ) ? filemtime( $script ) : RIVROSS_THEME_VERSION,
		true
	);
}
add_action( 'admin_enqueue_scripts', 'rivross_cpt_media_admin_assets' );

function rivross_enqueue_assets() {
	wp_enqueue_style(
		'rivross-fonts',
		'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=Inter:wght@400;500;600;700&family=Montserrat:wght@400;500;600;700&family=Playfair+Display:wght@500;600;700&display=swap',
		array(),
		null
	);

	/* Keep all hero banners free of the legacy yellow diagonal decoration. */
	$hero_shape_reset = get_template_directory() . '/assets/css/hero-shape-reset.css';
	wp_enqueue_style(
		'rivross-hero-shape-reset',
		get_template_directory_uri() . '/assets/css/hero-shape-reset.css',
		array( 'rivross-fonts' ),
		file_exists( $hero_shape_reset ) ? filemtime( $hero_shape_reset ) : RIVROSS_THEME_VERSION
	);

	if ( function_exists( 'rivross_should_render_maintenance' ) && rivross_should_render_maintenance() ) {
		$maintenance_style = get_template_directory() . '/assets/css/maintenance.css';
		wp_enqueue_style(
			'rivross-maintenance',
			get_template_directory_uri() . '/assets/css/maintenance.css',
			array( 'rivross-fonts' ),
			file_exists( $maintenance_style ) ? filemtime( $maintenance_style ) : RIVROSS_THEME_VERSION
		);
		return;
	}

	wp_enqueue_style(
		'rivross-style',
		get_stylesheet_uri(),
		array( 'rivross-fonts' ),
		filemtime( get_stylesheet_directory() . '/style.css' )
	);

	wp_enqueue_style(
		'rivross-header-footer',
		get_template_directory_uri() . '/assets/css/header-footer.css',
		array( 'rivross-style' ),
		filemtime( get_stylesheet_directory() . '/assets/css/header-footer.css' )
	);

	$navigation_script = get_template_directory() . '/assets/js/navigation.js';
	wp_enqueue_script(
		'rivross-navigation',
		get_template_directory_uri() . '/assets/js/navigation.js',
		array(),
		file_exists( $navigation_script ) ? filemtime( $navigation_script ) : RIVROSS_THEME_VERSION,
		true
	);

	if ( is_front_page() || is_page_template( 'page-home.php' ) ) {
		wp_enqueue_style(
			'rivross-home',
			get_template_directory_uri() . '/assets/css/home.css',
			array( 'rivross-header-footer' ),
			filemtime( get_stylesheet_directory() . '/assets/css/home.css' )
		);
		$carousel_script = get_template_directory() . '/assets/js/carousel.js';
		wp_enqueue_script(
			'rivross-carousel',
			get_template_directory_uri() . '/assets/js/carousel.js',
			array(),
			file_exists( $carousel_script ) ? filemtime( $carousel_script ) : RIVROSS_THEME_VERSION,
			true
		);
		$hero_carousel_script = get_template_directory() . '/assets/js/hero-carousel.js';
		wp_enqueue_script(
			'rivross-hero-carousel',
			get_template_directory_uri() . '/assets/js/hero-carousel.js',
			array(),
			file_exists( $hero_carousel_script ) ? filemtime( $hero_carousel_script ) : RIVROSS_THEME_VERSION,
			true
		);
	}

	if ( is_page( array( 'about-us', 'about' ) ) || is_page_template( array( 'page-about-us.php', 'page-about.php' ) ) ) {
		wp_enqueue_style(
			'rivross-about',
			get_template_directory_uri() . '/assets/css/about.css',
			array( 'rivross-header-footer' ),
			filemtime( get_stylesheet_directory() . '/assets/css/about.css' )
		);
	}

	if ( is_page( 'our-companies' ) || is_page_template( 'page-our-companies.php' ) ) {
		wp_enqueue_style(
			'rivross-companies',
			get_template_directory_uri() . '/assets/css/companies.css',
			array( 'rivross-header-footer' ),
			filemtime( get_stylesheet_directory() . '/assets/css/companies.css' )
		);
	}

	if ( is_home() || is_page( 'news-media' ) || is_page_template( 'page-news-media.php' ) ) {
		wp_enqueue_style(
			'rivross-news',
			get_template_directory_uri() . '/assets/css/news.css',
			array( 'rivross-header-footer' ),
			filemtime( get_stylesheet_directory() . '/assets/css/news.css' )
		);
	}

	if ( is_singular( 'post' ) ) {
		$news_single_style = get_template_directory() . '/assets/css/news-single.css';
		wp_enqueue_style(
			'rivross-news-single',
			get_template_directory_uri() . '/assets/css/news-single.css',
			array( 'rivross-header-footer' ),
			file_exists( $news_single_style ) ? filemtime( $news_single_style ) : RIVROSS_THEME_VERSION
		);
	}

	if ( is_page( 'contact-us' ) || is_page_template( 'page-contact-us.php' ) ) {
		wp_enqueue_style(
			'rivross-contact',
			get_template_directory_uri() . '/assets/css/contact.css',
			array( 'rivross-header-footer' ),
			filemtime( get_stylesheet_directory() . '/assets/css/contact.css' )
		);
		$faq_script = get_template_directory() . '/assets/js/faq.js';
		wp_enqueue_script(
			'rivross-faq',
			get_template_directory_uri() . '/assets/js/faq.js',
			array(),
			file_exists( $faq_script ) ? filemtime( $faq_script ) : RIVROSS_THEME_VERSION,
			true
		);
	}

	if ( is_page( 'management' ) || is_page_template( 'page-management.php' ) ) {
		wp_enqueue_style(
			'rivross-management',
			get_template_directory_uri() . '/assets/css/management.css',
			array( 'rivross-header-footer' ),
			filemtime( get_stylesheet_directory() . '/assets/css/management.css' )
		);
	}

	if ( is_page( 'careers' ) || is_page_template( 'page-careers.php' ) || is_singular( 'rivross_job' ) ) {
		$careers_style = get_template_directory() . '/assets/css/careers.css';
		wp_enqueue_style(
			'rivross-careers',
			get_template_directory_uri() . '/assets/css/careers.css',
			array( 'rivross-header-footer' ),
			file_exists( $careers_style ) ? filemtime( $careers_style ) : RIVROSS_THEME_VERSION
		);
		if ( is_page( 'careers' ) || is_page_template( 'page-careers.php' ) ) {
			$careers_jobs_script = get_template_directory() . '/assets/js/careers.js';
			wp_enqueue_script(
				'rivross-careers-jobs',
				get_template_directory_uri() . '/assets/js/careers.js',
				array(),
				file_exists( $careers_jobs_script ) ? filemtime( $careers_jobs_script ) : RIVROSS_THEME_VERSION,
				true
			);
			wp_localize_script(
				'rivross-careers-jobs',
				'RivrossCareersJobs',
				array(
					'ajaxUrl'        => admin_url( 'admin-ajax.php' ),
					'errorMessage'   => __( 'Jobs could not be loaded. Please try again.', 'rivross-corporate' ),
					'loadingMessage' => __( 'Loading jobs…', 'rivross-corporate' ),
				)
			);
		}
	}

	if ( is_singular( 'rivross_job' ) ) {
		$career_job_style = get_template_directory() . '/assets/css/career-job.css';
		wp_enqueue_style(
			'rivross-career-job',
			get_template_directory_uri() . '/assets/css/career-job.css',
			array( 'rivross-header-footer', 'rivross-careers' ),
			file_exists( $career_job_style ) ? filemtime( $career_job_style ) : RIVROSS_THEME_VERSION
		);
	}

	if ( is_page( 'submit-your-cv' ) || is_page_template( 'page-general-application.php' ) ) {
		$career_application_style = get_template_directory() . '/assets/css/career-application.css';
		wp_enqueue_style(
			'rivross-career-application',
			get_template_directory_uri() . '/assets/css/career-application.css',
			array( 'rivross-header-footer' ),
			file_exists( $career_application_style ) ? filemtime( $career_application_style ) : RIVROSS_THEME_VERSION
		);
	}

	if ( is_page( 'events' ) || is_page_template( 'page-events.php' ) || is_singular( 'rivross_event' ) ) {
		wp_enqueue_style(
			'rivross-events',
			get_template_directory_uri() . '/assets/css/events.css',
			array( 'rivross-header-footer' ),
			filemtime( get_stylesheet_directory() . '/assets/css/events.css' )
		);
		$events_script = get_template_directory() . '/assets/js/events.js';
		wp_enqueue_script(
			'rivross-events',
			get_template_directory_uri() . '/assets/js/events.js',
			array(),
			file_exists( $events_script ) ? filemtime( $events_script ) : RIVROSS_THEME_VERSION,
			true
		);
	}

	if ( is_page( 'real-estate' ) || is_page_template( 'page-real-estate.php' ) || is_singular( 'rivross_property' ) ) {
		$real_estate_style = get_template_directory() . '/assets/css/real-estate.css';
		wp_enqueue_style(
			'rivross-real-estate',
			get_template_directory_uri() . '/assets/css/real-estate.css',
			array( 'rivross-header-footer' ),
			file_exists( $real_estate_style ) ? filemtime( $real_estate_style ) : RIVROSS_THEME_VERSION
		);
	}

	if ( is_page( 'projects' ) || is_page_template( 'page-projects.php' ) || is_singular( 'rivross_project' ) ) {
		$projects_style = get_template_directory() . '/assets/css/projects.css';
		wp_enqueue_style(
			'rivross-projects',
			get_template_directory_uri() . '/assets/css/projects.css',
			array( 'rivross-header-footer' ),
			file_exists( $projects_style ) ? filemtime( $projects_style ) : RIVROSS_THEME_VERSION
		);
	}

	if ( is_page( 'travel-tourism' ) || is_page_template( 'page-travel-tourism.php' ) ) {
		$travel_style = get_template_directory() . '/assets/css/travel.css';
		wp_enqueue_style(
			'rivross-travel',
			get_template_directory_uri() . '/assets/css/travel.css',
			array( 'rivross-header-footer' ),
			file_exists( $travel_style ) ? filemtime( $travel_style ) : RIVROSS_THEME_VERSION
		);
	}

	if ( is_page( 'tea-business' ) || is_page_template( 'page-tea-business.php' ) ) {
		$tea_style = get_template_directory() . '/assets/css/tea.css';
		wp_enqueue_style(
			'rivross-tea',
			get_template_directory_uri() . '/assets/css/tea.css',
			array( 'rivross-header-footer' ),
			file_exists( $tea_style ) ? filemtime( $tea_style ) : RIVROSS_THEME_VERSION
		);
	}

	if ( is_page( array( 'terms-and-conditions', 'privacy-policy' ) ) || is_page_template( 'page-legal.php' ) ) {
		$legal_style = get_template_directory() . '/assets/css/legal.css';
		wp_enqueue_style(
			'rivross-legal',
			get_template_directory_uri() . '/assets/css/legal.css',
			array( 'rivross-header-footer' ),
			file_exists( $legal_style ) ? filemtime( $legal_style ) : RIVROSS_THEME_VERSION
		);
	}
}
add_action( 'wp_enqueue_scripts', 'rivross_enqueue_assets' );

/**
 * Add a light navigation layer to group page-specific Customizer sections.
 * WordPress supports one native panel level, so this keeps the existing
 * controls inside the RIVROSS panel while presenting a page-first hierarchy.
 *
 * @return void
 */
function rivross_customizer_controls_assets() {
	$script = get_template_directory() . '/assets/js/customizer-controls.js';
	$style  = get_template_directory() . '/assets/css/customizer-controls.css';

	/* The bulk partner-logo control uses the native WordPress Media Library. */
	wp_enqueue_media();

	wp_enqueue_script(
		'rivross-customizer-controls',
		get_template_directory_uri() . '/assets/js/customizer-controls.js',
		array( 'customize-controls', 'jquery' ),
		file_exists( $script ) ? filemtime( $script ) : RIVROSS_THEME_VERSION,
		true
	);
	wp_enqueue_style(
		'rivross-customizer-controls',
		get_template_directory_uri() . '/assets/css/customizer-controls.css',
		array( 'customize-controls' ),
		file_exists( $style ) ? filemtime( $style ) : RIVROSS_THEME_VERSION
	);
	wp_localize_script(
		'rivross-customizer-controls',
		'rivrossCustomizerL10n',
		array(
			'toolbarLabel' => __( 'Theme settings tools', 'rivross-corporate' ),
			'toolbarTip'   => __( 'Choose a page group below, then edit its content and publish your changes.', 'rivross-corporate' ),
			'expandAll'    => __( 'Expand all', 'rivross-corporate' ),
			'collapseAll'  => __( 'Collapse all', 'rivross-corporate' ),
			'partnerGalleryTitle'    => __( 'Choose partner logo images', 'rivross-corporate' ),
			'partnerGalleryUse'      => __( 'Use selected logos', 'rivross-corporate' ),
			'partnerGallerySelected' => __( 'logo images selected', 'rivross-corporate' ),
			'partnerGalleryEmpty'    => __( 'No logo images selected', 'rivross-corporate' ),
			'partnerGalleryRemove'   => __( 'Remove this logo', 'rivross-corporate' ),
			'partnerGalleryLimit'    => __( 'Only the first 8 selected logos were kept.', 'rivross-corporate' ),
		)
	);
}
add_action( 'customize_controls_enqueue_scripts', 'rivross_customizer_controls_assets' );

/**
 * Purge page-optimization caches after Customizer settings are published.
 *
 * Page templates read many of their values from theme mods. WordPress core
 * does not know which cached URLs depend on those options, so notify the
 * installed cache plugin when its public API is available. Both checks are
 * optional and do nothing when the corresponding plugin is not installed.
 */
function rivross_purge_caches_after_customizer_save() {
	if ( function_exists( 'rocket_clean_domain' ) ) {
		rocket_clean_domain();
	}

	if ( has_action( 'litespeed_purge_all' ) ) {
		do_action( 'litespeed_purge_all', 'RIVROSS Customizer settings updated' );
	}
}
add_action( 'customize_save_after', 'rivross_purge_caches_after_customizer_save', 20 );

function rivross_editor_assets() {
	add_editor_style( 'style.css' );
}
add_action( 'admin_init', 'rivross_editor_assets' );

function rivross_body_classes( $classes ) {
	$classes[] = 'rivross-theme';
	if ( is_page( 'tea-business' ) || is_page_template( 'page-tea-business.php' ) ) {
		$classes[] = 'rivross-tea-page';
	}
	return $classes;
}
add_filter( 'body_class', 'rivross_body_classes' );

/**
 * Resolve a Customizer link while keeping local section anchors on the site.
 *
 * @param string $url URL or a local #anchor.
 * @return string
 */
function rivross_theme_link( $url ) {
	$url = trim( (string) $url );
	if ( '' === $url ) {
		return '#';
	}
	/* Keep the primary About and Contact CTAs on their dedicated pages. */
	if ( in_array( strtolower( $url ), array( '#about', strtolower( home_url( '/#about' ) ) ), true ) ) {
		return home_url( '/about-us/' );
	}
	if ( in_array( strtolower( $url ), array( '#contact', strtolower( home_url( '/#contact' ) ) ), true ) ) {
		return home_url( '/contact-us/' );
	}
	if ( in_array( strtolower( $url ), array( '#travel', strtolower( home_url( '/#travel' ) ) ), true ) ) {
		return home_url( '/travel-tourism/' );
	}
	if ( in_array( strtolower( $url ), array( '#real-estate', strtolower( home_url( '/#real-estate' ) ) ), true ) ) {
		return home_url( '/real-estate/' );
	}
	if ( in_array( strtolower( $url ), array( '#tea', strtolower( home_url( '/#tea' ) ) ), true ) ) {
		return home_url( '/tea-business/' );
	}
	if ( in_array( strtolower( $url ), array( '#properties', strtolower( home_url( '/#properties' ) ) ), true ) ) {
		return home_url( '/real-estate/' );
	}
	if ( in_array( strtolower( $url ), array( '#projects', strtolower( home_url( '/#projects' ) ) ), true ) ) {
		return home_url( '/projects/' );
	}
	if ( in_array( strtolower( $url ), array( '#open-positions', strtolower( home_url( '/#open-positions' ) ) ), true ) ) {
		return home_url( '/careers/#open-positions' );
	}
	if ( 0 === strpos( $url, '#' ) ) {
		return home_url( '/' . $url );
	}
	return $url;
}

function rivross_primary_menu_fallback() {
	$items = array(
		__( 'Home', 'rivross-corporate' )          => home_url( '/' ),
		__( 'About Us', 'rivross-corporate' )      => home_url( '/about-us/' ),
		__( 'Our Companies', 'rivross-corporate' ) => home_url( '/our-companies/' ),
		__( 'Projects', 'rivross-corporate' )      => home_url( '/projects/' ),
		__( 'Management', 'rivross-corporate' )    => home_url( '/management/' ),
		__( 'News & Media', 'rivross-corporate' )  => home_url( '/news-media/' ),
		__( 'Contact Us', 'rivross-corporate' )    => home_url( '/contact-us/' ),
	);
	$companies = array(
		__( 'Real Estate', 'rivross-corporate' )     => home_url( '/real-estate/' ),
		__( 'Travel & Tourism', 'rivross-corporate' ) => home_url( '/travel-tourism/' ),
		__( 'Tea Business', 'rivross-corporate' )   => home_url( '/tea-business/' ),
	);

	echo '<ul class="site-nav__list">';
	foreach ( $items as $label => $url ) {
		if ( strtolower( $label ) === strtolower( __( 'Our Companies', 'rivross-corporate' ) ) ) {
			echo '<li class="menu-item menu-item-has-children"><a href="' . esc_url( $url ) . '">' . esc_html( $label ) . '</a><ul class="sub-menu">';
			foreach ( $companies as $child_label => $child_url ) {
				echo '<li class="menu-item"><a href="' . esc_url( $child_url ) . '">' . esc_html( $child_label ) . '</a></li>';
			}
			echo '</ul></li>';
			continue;
		}
		echo '<li class="menu-item"><a href="' . esc_url( $url ) . '">' . esc_html( $label ) . '</a></li>';
	}
	echo '</ul>';
}

/**
 * Group the three business pages beneath Our Companies in a saved WordPress menu.
 *
 * @param array    $items Menu items.
 * @param stdClass $args  Menu arguments.
 * @return array
 */
function rivross_prepare_companies_submenu( $items, $args ) {
	if ( empty( $args->theme_location ) || 'primary' !== $args->theme_location || empty( $items ) ) {
		return $items;
	}

	$parent       = null;
	$parent_index = null;
	$matches      = array( 'real-estate' => null, 'travel-tourism' => null, 'tea-business' => null );
	$labels       = array(
		'real-estate'    => __( 'Real Estate', 'rivross-corporate' ),
		'travel-tourism' => __( 'Travel & Tourism', 'rivross-corporate' ),
		'tea-business'   => __( 'Tea Business', 'rivross-corporate' ),
	);
	$urls = array(
		'real-estate'    => home_url( '/real-estate/' ),
		'travel-tourism' => home_url( '/travel-tourism/' ),
		'tea-business'   => home_url( '/tea-business/' ),
	);

	foreach ( $items as $index => $item ) {
		$title = strtolower( trim( wp_strip_all_tags( (string) $item->title ) ) );
		$url   = strtolower( (string) $item->url );
		if ( null === $parent && ( 'our companies' === $title || false !== strpos( $url, '/our-companies/' ) ) ) {
			$parent       = $item;
			$parent_index = $index;
		}
		foreach ( array_keys( $matches ) as $key ) {
			if ( null === $matches[ $key ] && ( false !== strpos( $url, '/' . $key . '/' ) || $title === strtolower( $labels[ $key ] ) ) ) {
				$matches[ $key ] = $item;
			}
		}
	}

	if ( ! $parent ) {
		return $items;
	}

	$parent_id = (int) $parent->ID;
	$children  = array();
	$used_ids  = array();
	$child_num = 0;
	foreach ( $matches as $key => $matched ) {
		$child = $matched ? $matched : clone $parent;
		if ( ! $matched ) {
			$child_num++;
			$child->ID              = -1000 - $child_num;
			$child->db_id           = $child->ID;
			$child->object_id       = 0;
			$child->object          = 'custom';
			$child->type            = 'custom';
			$child->type_label      = __( 'Custom Link', 'rivross-corporate' );
			$child->menu_order      = $parent->menu_order + $child_num;
			$child->classes         = array( 'menu-item' );
			$child->current         = false;
			$child->current_item_ancestor = false;
			$child->current_item_parent   = false;
		}
		$child->title              = $labels[ $key ];
		$child->url                = $urls[ $key ];
		$child->menu_item_parent   = (string) $parent_id;
		$child->classes            = is_array( $child->classes ) ? array_values( array_diff( $child->classes, array( 'menu-item-has-children', 'current-menu-ancestor', 'current-menu-parent' ) ) ) : array( 'menu-item' );
		$child->classes[]          = 'menu-item-company-link';
		$is_current                = ( is_page( $key ) || ( 'real-estate' === $key && is_singular( 'rivross_property' ) ) );
		$child->current            = $is_current;
		if ( $is_current && ! in_array( 'current-menu-item', $child->classes, true ) ) {
			$child->classes[] = 'current-menu-item';
		}
		$children[] = $child;
		$used_ids[ (string) $child->ID ] = true;
	}

	$parent->classes = is_array( $parent->classes ) ? $parent->classes : array( 'menu-item' );
	if ( ! in_array( 'menu-item-has-children', $parent->classes, true ) ) {
		$parent->classes[] = 'menu-item-has-children';
	}
	if ( array_filter( $children, static function ( $child ) { return ! empty( $child->current ); } ) && ! in_array( 'current-menu-ancestor', $parent->classes, true ) ) {
		$parent->classes[] = 'current-menu-ancestor';
	}

	$updated = array();
	foreach ( $items as $index => $item ) {
		if ( $index === $parent_index ) {
			$updated[] = $parent;
			foreach ( $children as $child ) {
				$updated[] = $child;
			}
			continue;
		}
		if ( isset( $used_ids[ (string) $item->ID ] ) ) {
			continue;
		}
		$updated[] = $item;
	}

	return $updated;
}
add_filter( 'wp_nav_menu_objects', 'rivross_prepare_companies_submenu', 6, 2 );

/**
 * Keep the dedicated property portal discoverable when an older saved menu
 * does not yet contain the Real Estate item.
 *
 * @param string   $items Menu HTML.
 * @param stdClass $args  Menu arguments.
 * @return string
 */
function rivross_add_real_estate_menu_item( $items, $args ) {
	if ( empty( $args->theme_location ) || 'primary' !== $args->theme_location || false !== strpos( $items, '/real-estate/' ) ) {
		return $items;
	}
	$current = ( is_page( 'real-estate' ) || is_singular( 'rivross_property' ) ) ? ' current-menu-item' : '';
	$item    = '<li class="menu-item menu-item-real-estate' . esc_attr( $current ) . '"><a href="' . esc_url( home_url( '/real-estate/' ) ) . '">' . esc_html__( 'Real Estate', 'rivross-corporate' ) . '</a></li>';
	$updated = preg_replace( '/(<li[^>]*>\s*<a[^>]*>\s*Our Companies\s*<\/a>\s*<\/li>)/i', '$1' . $item, $items, 1 );
	return $updated ? $updated : $items . $item;
}
add_filter( 'wp_nav_menu_items', 'rivross_add_real_estate_menu_item', 10, 2 );

/**
 * Keep Careers discoverable in the footer quick links while the saved menu
 * is being maintained in the WordPress menu editor.
 *
 * @param string   $items Menu HTML.
 * @param stdClass $args  Menu arguments.
 * @return string
 */
function rivross_add_careers_footer_menu_item( $items, $args ) {
	if ( empty( $args->theme_location ) || 'footer' !== $args->theme_location || false !== strpos( $items, '/careers/' ) ) {
		return $items;
	}
	$current = is_page( 'careers' ) ? ' current-menu-item' : '';
	$item    = '<li class="menu-item menu-item-careers' . esc_attr( $current ) . '"><a href="' . esc_url( home_url( '/careers/' ) ) . '">' . esc_html__( 'Careers', 'rivross-corporate' ) . '</a></li>';
	$updated = preg_replace( '/(<li[^>]*>\s*<a[^>]*>\s*Contact Us\s*<\/a>\s*<\/li>)/i', $item . '$1', $items, 1 );
	return $updated ? $updated : $items . $item;
}
add_filter( 'wp_nav_menu_items', 'rivross_add_careers_footer_menu_item', 11, 2 );

/**
 * Prevent empty saved menu entries from leaving blank rows in the header or footer.
 *
 * @param array    $items Menu items.
 * @param stdClass $args  Menu arguments.
 * @return array
 */
function rivross_remove_empty_menu_items( $items, $args ) {
	if ( empty( $args->theme_location ) || ! in_array( $args->theme_location, array( 'primary', 'footer' ), true ) ) {
		return $items;
	}

	return array_values(
		array_filter(
			$items,
			static function ( $item ) use ( $args ) {
				$title = strtolower( trim( wp_strip_all_tags( (string) $item->title ) ) );
				if ( 'primary' === $args->theme_location && ( 'services' === $title || false !== strpos( strtolower( (string) $item->url ), '#services' ) ) ) {
					return false;
				}
				return '' !== $title;
			}
		)
	);
}
add_filter( 'wp_nav_menu_objects', 'rivross_remove_empty_menu_items', 5, 2 );

function rivross_link_projects_menu_item( $items, $args ) {
	if ( empty( $args->theme_location ) || ! in_array( $args->theme_location, array( 'primary', 'footer' ), true ) ) { return $items; }
	foreach ( $items as $item ) {
		if ( 'Projects' === trim( wp_strip_all_tags( $item->title ) ) && false !== strpos( (string) $item->url, '#projects' ) ) {
			$item->url = home_url( '/projects/' );
			if ( is_page( 'projects' ) || is_singular( 'rivross_project' ) ) { $item->classes[] = 'current-menu-item'; }
		}
	}
	return $items;
}
add_filter( 'wp_nav_menu_objects', 'rivross_link_projects_menu_item', 10, 2 );

function rivross_footer_menu_fallback() {
	$items = array(
		__( 'Home', 'rivross-corporate' )          => home_url( '/' ),
		__( 'About Us', 'rivross-corporate' )      => home_url( '/about-us/' ),
		__( 'Our Companies', 'rivross-corporate' ) => home_url( '/our-companies/' ),
		__( 'Real Estate', 'rivross-corporate' )     => home_url( '/real-estate/' ),
		__( 'Management', 'rivross-corporate' )    => home_url( '/management/' ),
		__( 'Projects', 'rivross-corporate' )      => home_url( '/projects/' ),
		__( 'Careers', 'rivross-corporate' )       => home_url( '/careers/' ),
		__( 'Contact Us', 'rivross-corporate' )    => home_url( '/contact-us/' ),
	);

	echo '<ul class="footer-links">';
	foreach ( $items as $label => $url ) {
		echo '<li><a href="' . esc_url( $url ) . '">' . esc_html( $label ) . '</a></li>';
	}
	echo '</ul>';
}

function rivross_icon( $name, $class = '' ) {
	$icons = array(
		'arrow'     => '<path d="M4 12h15M13 6l6 6-6 6"/>',
		'building'  => '<path d="M4 21V5l8-3 8 3v16M8 21v-4h8v4M8 8h2M14 8h2M8 12h2M14 12h2"/>',
		'eye'       => '<path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/>',
		'target'    => '<circle cx="12" cy="12" r="8.5"/><circle cx="12" cy="12" r="4.5"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/>',
		'flag'      => '<path d="M5 21V4m0 0c4-3 7 3 14 0v9c-7 3-10-3-14 0"/>',
		'users'     => '<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3.5 20c.4-3.6 2.2-5.5 5.5-5.5s5.1 1.9 5.5 5.5M14 15c3.5-.5 5.7 1.1 6.5 5"/>',
		'handshake' => '<path d="m4 10 3-3 4 2 2-2 4 3 3-3M3 11l4 4 2-2 3 3 3-3 3 2 3-4M7 7l2-3 4 2 2-2 3 3"/>',
		'chart'     => '<path d="M4 20V10M10 20V6M16 20V12M22 20H2"/>',
		'shield'    => '<path d="M12 3 20 6v5c0 5-3.3 8.5-8 10-4.7-1.5-8-5-8-10V6l8-3Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/>',
		'plane'     => '<path d="m3 11 18-7-7 18-3-8-8-3Z"/><path d="M11 14 7 21"/>',
		'leaf'      => '<path d="M20 4C12 4 6 7 5 13c-.7 4.3 2.3 7 6.2 6.2C17 18 20 12 20 4Z"/><path d="M4 21c3-4.5 6.5-7 11-9"/>',
		'award'     => '<circle cx="12" cy="9" r="5"/><path d="m8 13-1 8 5-3 5 3-1-8"/><path d="m12 6 1 2h2l-1.6 1.3.6 2L12 10l-2 1.3.6-2L9 8h2l1-2Z"/>',
		'gear'      => '<path d="m12 3 1.2 2.1 2.4.5 1.8-1.1 2 2-1.1 1.8.5 2.4L21 12l-2.1 1.2-.5 2.4 1.1 1.8-2 2-1.8-1.1-2.4.5L12 21l-1.2-2.1-2.4-.5-1.8 1.1-2-2 1.1-1.8-.5-2.4L3 12l2.1-1.2.5-2.4-1.1-1.8 2-2 1.8 1.1 2.4-.5L12 3Z"/><circle cx="12" cy="12" r="3"/>',
		'headset'   => '<path d="M4 13a8 8 0 0 1 16 0v4M4 14h3v5H5a1 1 0 0 1-1-1v-4ZM20 14h-3v5h2a1 1 0 0 0 1-1v-4ZM17 20c-1 .8-2.6 1-4 1"/>',
		'sprout'    => '<path d="M12 21V10M12 13c-4 0-7-2-7-7 4 0 7 2 7 7ZM12 10c0-4 3-7 7-7 0 4-3 7-7 7Z"/>',
		'hotel'     => '<path d="M4 20V5h16v15M4 10h16M8 7h2M14 7h2M8 13h2M14 13h2M2 20h20"/>',
		'suitcase'  => '<rect x="4" y="7" width="16" height="13" rx="2"/><path d="M9 7V4h6v3M8 12h8M8 16h8"/>',
		'kaaba'     => '<path d="m4 8 8-4 8 4-8 4-8-4ZM4 8v9l8 4 8-4V8M8 10v9M16 10v7"/>',
		'briefcase' => '<rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V4h8v3M3 12h18M10 12v3h4v-3"/>',
		'globe'     => '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.4 2.5 3.5 5.5 3.5 9S14.4 18.5 12 21c-2.4-2.5-3.5-5.5-3.5-9S9.6 5.5 12 3Z"/>',
		'phone'     => '<path d="M6.5 3.5 9 3l2 4-2 1.5a14.6 14.6 0 0 0 5 5L15.5 12l4 2-.5 2.5c-.3 1.3-1.5 2-2.7 1.7C10 17 7 14 5.8 7.7 5.5 6.5 5.2 4.8 6.5 3.5Z"/>',
		'mail'      => '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/>',
		'pin'       => '<path d="M12 21s7-6.1 7-12a7 7 0 1 0-14 0c0 5.9 7 12 7 12Z"/><circle cx="12" cy="9" r="2.3"/>',
		'clock'     => '<circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3 2"/>',
		'download'  => '<path d="M12 3v11M8 10l4 4 4-4M5 19h14"/>',
		'check'     => '<path d="m5 12 4 4L19 6"/>',
		'grid'      => '<rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/>',
		'folder'    => '<path d="M3 7.5A2.5 2.5 0 0 1 5.5 5H10l2 2h6.5A2.5 2.5 0 0 1 21 9.5v8A2.5 2.5 0 0 1 18.5 20h-13A2.5 2.5 0 0 1 3 17.5v-10Z"/>',
		'calendar'  => '<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/>',
		'search'    => '<circle cx="10.8" cy="10.8" r="6.3"/><path d="m16 16 4.5 4.5"/>',
		'news'      => '<path d="M5 4h14a2 2 0 0 1 2 2v13H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/><path d="M7 8h10M7 12h10M7 16h6"/>',
		'lightbulb' => '<path d="M9 18h6M10 21h4M8.5 14.5C7.5 13.5 7 12.2 7 10.7a5 5 0 0 1 10 0c0 1.5-.5 2.8-1.5 3.8-.8.8-1.2 1.5-1.4 2.5h-4.2c-.2-1-.6-1.7-1.4-2.5Z"/>',
		'microphone' => '<path d="M9 4a3 3 0 0 1 6 0v8a3 3 0 0 1-6 0V4Z"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3M8 21h8"/>',
		// Brand marks use a filled silhouette. The shared SVG defaults to an
		// outline for utility icons, so explicitly set the fill on these paths
		// to keep social icons crisp at small sizes and during hover states.
		'facebook'  => '<path fill="currentColor" stroke="none" d="M14 8h3V4h-3c-3 0-5 2-5 5v3H6v4h3v4h4v-4h3l1-4h-4V9c0-.7.3-1 1-1Z"/>',
		'linkedin'  => '<path transform="translate(3 0)" fill="currentColor" stroke="none" d="M5 8H2v12h3V8Zm.2-3.5A1.7 1.7 0 1 1 1.8 4.5a1.7 1.7 0 0 1 3.4 0ZM9 8H6v12h3v-6c0-1.7.4-3 2.2-3 1.7 0 1.8 1.4 1.8 3v6h3v-6.5c0-3.2-.7-5.5-4.3-5.5-1.5 0-2.5.8-2.7 1.4V8Z"/>',
		'whatsapp'  => '<path d="M20.5 3.5A11.3 11.3 0 0 0 12.4 1 11.4 11.4 0 0 0 2.5 17.8L1 23l5.3-1.4A11.4 11.4 0 1 0 20.5 3.5Z"/><path d="M8.5 8.5c.2-.4.4-.4.7-.4h.5c.2 0 .4.1.5.4l.7 1.6c.1.2.1.4-.1.6l-.6.7c.8 1.3 1.8 2.3 3.1 3.1l.7-.6c.2-.2.4-.2.6-.1l1.6.7c.3.1.4.3.4.5v.5c0 .3 0 .5-.4.7-.4.2-1.3.4-2.3.1-1.1-.2-2.5-1-3.8-2.3-1.3-1.3-2.1-2.7-2.3-3.8-.3-1 .0-1.9.2-2.3Z"/>',
		'youtube'   => '<path d="M21 8.2a2.6 2.6 0 0 0-1.8-1.8C17.6 6 12 6 12 6s-5.6 0-7.2.4A2.6 2.6 0 0 0 3 8.2 27 27 0 0 0 2.6 12c0 1.4.1 2.7.4 3.8a2.6 2.6 0 0 0 1.8 1.8c1.6.4 7.2.4 7.2.4s5.6 0 7.2-.4a2.6 2.6 0 0 0 1.8-1.8c.3-1.1.4-2.4.4-3.8s-.1-2.7-.4-3.8Z"/><path fill="currentColor" stroke="none" d="m10 15 5-3-5-3v6Z"/>',
		'instagram' => '<rect x="4" y="4" width="16" height="16" rx="4"/><circle cx="12" cy="12" r="3.5"/><circle cx="17.2" cy="6.8" r=".8"/>',
		'heart'     => '<path d="M20.8 8.7c0 5.2-8.8 10.2-8.8 10.2S3.2 13.9 3.2 8.7A4.7 4.7 0 0 1 12 6.1a4.7 4.7 0 0 1 8.8 2.6Z"/>',
		'bed'       => '<path d="M4 18v-8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8M4 14h16M7 11h3"/>',
		'bath'      => '<path d="M4 13h16v3a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3v-3ZM6 13V6a2 2 0 0 1 4 0v1M4 20v1M20 20v1"/>',
		'car'       => '<path d="m5 16 1.3-5.2A2 2 0 0 1 8.2 9h7.6a2 2 0 0 1 1.9 1.8L19 16M3 16h18v4H3zM6 20v1M18 20v1M6 16h.01M18 16h.01"/>',
		'ruler'     => '<path d="m4 16 12-12 4 4L8 20H4v-4Z"/><path d="m9 15 2 2M12 12l2 2M15 9l2 2"/>',
		'money'     => '<circle cx="12" cy="12" r="8.5"/><path d="M12 7v10M15 9.2c-.7-.6-1.5-.9-2.5-.9-1.4 0-2.5.7-2.5 1.8 0 2.8 5 1 5 3.8 0 1.1-1 1.8-2.5 1.8-1 0-1.8-.3-2.5-.9"/>',
		'map'       => '<path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Z"/><path d="M9 3v15M15 6v15"/>',
		'image'     => '<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m3 16 5-5 4 4 3-3 6 6"/>',
		'file'      => '<path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 13h6M9 17h6"/>',
	);

	if ( ! isset( $icons[ $name ] ) ) {
		return '';
	}

	return '<svg class="rivross-icon ' . esc_attr( $class ) . '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">' . $icons[ $name ] . '</svg>';
}
