<?php
/**
 * Real Estate property portal page.
 *
 * @package Rivross_Corporate
 */

get_header();

$page_url = get_permalink();
$assets   = get_theme_file_uri( '/assets/images/' );
$hero_image = get_theme_mod( 'rivross_real_estate_hero_image', $assets . 'real-estate/real-estate-hero.png' );
$search_term = isset( $_GET['property_s'] ) ? sanitize_text_field( wp_unslash( $_GET['property_s'] ) ) : '';
$location   = isset( $_GET['property_location'] ) ? sanitize_text_field( wp_unslash( $_GET['property_location'] ) ) : '';
$type       = isset( $_GET['property_type'] ) ? sanitize_title( wp_unslash( $_GET['property_type'] ) ) : '';
$status     = isset( $_GET['property_status'] ) ? sanitize_text_field( wp_unslash( $_GET['property_status'] ) ) : '';
$sort       = isset( $_GET['property_sort'] ) ? sanitize_key( wp_unslash( $_GET['property_sort'] ) ) : 'latest';
$types      = get_terms( array( 'taxonomy' => 'rivross_property_type', 'hide_empty' => true ) );
$types      = is_wp_error( $types ) ? array() : $types;
$location_posts = get_posts( array( 'post_type' => 'rivross_property', 'post_status' => 'publish', 'posts_per_page' => -1, 'orderby' => 'title', 'order' => 'ASC' ) );
$locations = array();
foreach ( $location_posts as $location_post ) {
	$property_location = rivross_property_meta( $location_post->ID, 'location' );
	if ( $property_location && ! in_array( $property_location, $locations, true ) ) { $locations[] = $property_location; }
}
$query_args = array( 'post_type' => 'rivross_property', 'post_status' => 'publish', 'posts_per_page' => 12, 'paged' => max( 1, get_query_var( 'paged' ) ) );
if ( $search_term ) { $query_args['s'] = $search_term; }
if ( $location ) { $query_args['meta_query'][] = array( 'key' => '_rivross_property_location', 'value' => $location ); }
if ( $status ) { $query_args['meta_query'][] = array( 'key' => '_rivross_property_status', 'value' => $status ); }
if ( $type ) { $query_args['tax_query'] = array( array( 'taxonomy' => 'rivross_property_type', 'field' => 'slug', 'terms' => $type ) ); }
if ( 'price-low' === $sort ) { $query_args['meta_key'] = '_rivross_property_price_value'; $query_args['orderby'] = 'meta_value_num'; $query_args['order'] = 'ASC'; }
elseif ( 'price-high' === $sort ) { $query_args['meta_key'] = '_rivross_property_price_value'; $query_args['orderby'] = 'meta_value_num'; $query_args['order'] = 'DESC'; }
else { $query_args['orderby'] = 'date'; $query_args['order'] = 'DESC'; }
$properties = new WP_Query( $query_args );
$filter_url = static function ( $overrides = array() ) use ( $page_url, $search_term, $location, $type, $status, $sort ) {
	$args = array( 'property_s' => $search_term, 'property_location' => $location, 'property_type' => $type, 'property_status' => $status, 'property_sort' => $sort );
	foreach ( $overrides as $key => $value ) { $args[ $key ] = $value; }
	return add_query_arg( array_filter( $args ), $page_url );
};
$why_items = array(
	array( 'pin', __( 'Prime Locations', 'rivross-corporate' ), __( 'Properties in the most desirable areas.', 'rivross-corporate' ) ),
	array( 'shield', __( 'Trusted Developer', 'rivross-corporate' ), __( 'Commitment to quality, transparency and trust.', 'rivross-corporate' ) ),
	array( 'money', __( 'High ROI', 'rivross-corporate' ), __( 'Strong rental yield and capital appreciation.', 'rivross-corporate' ) ),
	array( 'file', __( 'Legal Security', 'rivross-corporate' ), __( '100% legal property with clear documentation.', 'rivross-corporate' ) ),
	array( 'headset', __( 'After Sales Support', 'rivross-corporate' ), __( 'Dedicated support even after possession.', 'rivross-corporate' ) ),
);
?>

<section class="property-hero" style="--property-hero-image:url('<?php echo esc_url( $hero_image ); ?>');">
	<div class="rivross-container rivross-container--wide property-hero__inner">
		<nav class="property-hero__breadcrumb" aria-label="<?php esc_attr_e( 'Breadcrumb', 'rivross-corporate' ); ?>"><a href="<?php echo esc_url( home_url( '/' ) ); ?>"><?php echo esc_html( get_theme_mod( 'rivross_real_estate_breadcrumb_home', __( 'Home', 'rivross-corporate' ) ) ); ?></a><span>›</span><a href="<?php echo esc_url( home_url( '/our-companies/' ) ); ?>"><?php echo esc_html( get_theme_mod( 'rivross_real_estate_breadcrumb_parent', __( 'Our Companies', 'rivross-corporate' ) ) ); ?></a><span>›</span><span><?php echo esc_html( get_theme_mod( 'rivross_real_estate_breadcrumb_page', __( 'Real Estate', 'rivross-corporate' ) ) ); ?></span></nav>
		<div class="property-hero__copy"><h1><span><?php echo esc_html( get_theme_mod( 'rivross_real_estate_hero_line_1', __( 'Properties', 'rivross-corporate' ) ) ); ?></span><strong><?php echo esc_html( get_theme_mod( 'rivross_real_estate_hero_line_2', __( 'Find Your Perfect Property', 'rivross-corporate' ) ) ); ?></strong></h1><i></i><p><?php echo esc_html( get_theme_mod( 'rivross_real_estate_hero_description', __( 'Explore our wide range of residential, commercial and land properties in prime locations.', 'rivross-corporate' ) ) ); ?></p></div>
	</div>
</section>

<div class="property-page">
	<section class="property-filters"><div class="rivross-container rivross-container--wide"><form method="get" action="<?php echo esc_url( $page_url ); ?>" class="property-filters__form">
		<label><span><?php esc_html_e( 'Location', 'rivross-corporate' ); ?></span><select name="property_location"><option value=""><?php esc_html_e( 'All Locations', 'rivross-corporate' ); ?></option><?php foreach ( $locations as $item ) : ?><option value="<?php echo esc_attr( $item ); ?>" <?php selected( $location, $item ); ?>><?php echo esc_html( $item ); ?></option><?php endforeach; ?></select></label>
		<label><span><?php esc_html_e( 'Property Type', 'rivross-corporate' ); ?></span><select name="property_type"><option value=""><?php esc_html_e( 'All Types', 'rivross-corporate' ); ?></option><?php foreach ( $types as $term ) : ?><option value="<?php echo esc_attr( $term->slug ); ?>" <?php selected( $type, $term->slug ); ?>><?php echo esc_html( $term->name ); ?></option><?php endforeach; ?></select></label>
		<label><span><?php esc_html_e( 'Status', 'rivross-corporate' ); ?></span><select name="property_status"><option value=""><?php esc_html_e( 'All Status', 'rivross-corporate' ); ?></option><?php foreach ( array( 'Ongoing', 'Upcoming', 'Completed', 'Ready' ) as $item ) : ?><option value="<?php echo esc_attr( $item ); ?>" <?php selected( $status, $item ); ?>><?php echo esc_html( $item ); ?></option><?php endforeach; ?></select></label>
		<label><span><?php esc_html_e( 'Price Range', 'rivross-corporate' ); ?></span><select name="property_sort"><option value="latest" <?php selected( $sort, 'latest' ); ?>><?php esc_html_e( 'Latest', 'rivross-corporate' ); ?></option><option value="price-low" <?php selected( $sort, 'price-low' ); ?>><?php esc_html_e( 'Price: Low to High', 'rivross-corporate' ); ?></option><option value="price-high" <?php selected( $sort, 'price-high' ); ?>><?php esc_html_e( 'Price: High to Low', 'rivross-corporate' ); ?></option></select></label>
		<label class="property-filters__search"><span><?php esc_html_e( 'Search', 'rivross-corporate' ); ?></span><input type="search" name="property_s" value="<?php echo esc_attr( $search_term ); ?>" placeholder="<?php esc_attr_e( 'Search properties...', 'rivross-corporate' ); ?>"></label><button class="rivross-button" type="submit"><?php esc_html_e( 'Search Properties', 'rivross-corporate' ); ?> <?php echo rivross_icon( 'search' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></button>
	</form></div></section>

	<section class="property-content"><div class="rivross-container rivross-container--wide property-content__grid"><main><div class="property-list-heading"><p><?php printf( esc_html__( 'Showing %1$d Properties', 'rivross-corporate' ), (int) $properties->found_posts ); ?></p><label><?php esc_html_e( 'Sort by:', 'rivross-corporate' ); ?><select onchange="if(this.value) window.location.href=this.value"><option value="<?php echo esc_url( $filter_url( array( 'property_sort' => 'latest' ) ) ); ?>" <?php selected( $sort, 'latest' ); ?>><?php esc_html_e( 'Latest', 'rivross-corporate' ); ?></option><option value="<?php echo esc_url( $filter_url( array( 'property_sort' => 'price-low' ) ) ); ?>" <?php selected( $sort, 'price-low' ); ?>><?php esc_html_e( 'Price: Low to High', 'rivross-corporate' ); ?></option><option value="<?php echo esc_url( $filter_url( array( 'property_sort' => 'price-high' ) ) ); ?>" <?php selected( $sort, 'price-high' ); ?>><?php esc_html_e( 'Price: High to Low', 'rivross-corporate' ); ?></option></select></label></div>
		<?php if ( $properties->have_posts() ) : ?><div class="property-grid"><?php while ( $properties->have_posts() ) : $properties->the_post(); $property_id = get_the_ID(); $terms = get_the_terms( $property_id, 'rivross_property_type' ); $type_label = ! empty( $terms ) && ! is_wp_error( $terms ) ? $terms[0]->name : rivross_property_meta( $property_id, 'type', __( 'Property', 'rivross-corporate' ) ); $status_label = rivross_property_meta( $property_id, 'status', 'Ongoing' ); ?>
			<article class="property-card"><a class="property-card__media" href="<?php the_permalink(); ?>"><img src="<?php echo esc_url( rivross_property_image_url( $property_id ) ); ?>" alt="<?php echo esc_attr( get_the_title() ); ?>" loading="lazy"><span class="property-card__type"><?php echo esc_html( $type_label ); ?></span><span class="property-card__status"><?php echo esc_html( $status_label ); ?></span><span class="property-card__favorite" aria-hidden="true"><?php echo rivross_icon( 'heart' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></span></a><div class="property-card__body"><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2><p class="property-card__location"><?php echo rivross_icon( 'pin' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><?php echo esc_html( rivross_property_meta( $property_id, 'location' ) ); ?></p><div class="property-card__specs"><span><?php echo rivross_icon( 'bed' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><?php echo esc_html( rivross_property_meta( $property_id, 'bedrooms' ) ); ?></span><span><?php echo rivross_icon( 'ruler' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><?php echo esc_html( rivross_property_meta( $property_id, 'size' ) ); ?></span><span><?php echo rivross_icon( 'car' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><?php echo esc_html( rivross_property_meta( $property_id, 'parking' ) ); ?></span></div><strong class="property-card__price"><?php echo esc_html( rivross_property_meta( $property_id, 'price' ) ); ?></strong><a class="property-card__link" href="<?php the_permalink(); ?>"><?php esc_html_e( 'View Details', 'rivross-corporate' ); ?> <?php echo rivross_icon( 'arrow' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></a></div></article>
		<?php endwhile; wp_reset_postdata(); ?></div><?php else : ?><div class="property-empty"><h2><?php esc_html_e( 'No properties found', 'rivross-corporate' ); ?></h2><p><?php esc_html_e( 'Try a different location, type or search term.', 'rivross-corporate' ); ?></p></div><?php endif; ?>
		</main><aside class="property-sidebar"><section class="property-sidebar__panel"><h2><?php esc_html_e( 'Property Categories', 'rivross-corporate' ); ?></h2><?php foreach ( $types as $term ) : ?><a href="<?php echo esc_url( $filter_url( array( 'property_type' => $term->slug ) ) ); ?>"><span><?php echo rivross_icon( 'building' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><?php echo esc_html( $term->name ); ?></span><b><?php echo esc_html( $term->count ); ?></b></a><?php endforeach; ?></section><section class="property-inquiry"><span class="property-inquiry__eyebrow"><?php esc_html_e( 'Looking for a property?', 'rivross-corporate' ); ?></span><h2><?php esc_html_e( 'Let us help you find the right fit.', 'rivross-corporate' ); ?></h2><p><?php esc_html_e( 'Fill out the form and our property experts will help you find the perfect property.', 'rivross-corporate' ); ?></p><a class="rivross-button" href="<?php echo esc_url( home_url( '/contact-us/#contact-form' ) ); ?>"><?php esc_html_e( 'Send Inquiry', 'rivross-corporate' ); ?> <?php echo rivross_icon( 'arrow' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></a></section><section class="property-help"><span><?php echo rivross_icon( 'headset' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></span><div><h2><?php esc_html_e( 'Need Help?', 'rivross-corporate' ); ?></h2><p><?php esc_html_e( 'Our property experts are ready to assist you.', 'rivross-corporate' ); ?></p><a href="tel:<?php echo esc_attr( preg_replace( '/[^0-9+]/', '', get_theme_mod( 'rivross_contact_phone', '01796-566279' ) ) ); ?>"><?php echo esc_html( get_theme_mod( 'rivross_contact_phone', '01796-566279' ) ); ?></a></div></section></aside></div></section>

	<section class="property-why"><div class="rivross-container rivross-container--wide"><div class="property-centered-heading"><span><?php echo esc_html( get_theme_mod( 'rivross_real_estate_why_heading', __( 'Why Invest With RIVROSS Real Estate?', 'rivross-corporate' ) ) ); ?></span></div><div class="property-why__grid"><?php foreach ( $why_items as $index => $item ) : $number = $index + 1; $why_icon = get_theme_mod( 'rivross_real_estate_why_' . $number . '_icon', $item[0] ); $why_title = get_theme_mod( 'rivross_real_estate_why_' . $number . '_title', $item[1] ); $why_description = get_theme_mod( 'rivross_real_estate_why_' . $number . '_description', $item[2] ); ?><div class="property-why__item"><i><?php echo rivross_icon( rivross_sanitize_icon_choice( $why_icon ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></i><h3><?php echo esc_html( $why_title ); ?></h3><p><?php echo esc_html( $why_description ); ?></p></div><?php endforeach; ?></div></div></section>
	<section class="property-newsletter"><div class="rivross-container rivross-container--wide"><span><?php echo rivross_icon( 'mail' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></span><div><h2><?php echo esc_html( get_theme_mod( 'rivross_real_estate_newsletter_title', __( 'Get Latest Property Updates', 'rivross-corporate' ) ) ); ?></h2><p><?php echo esc_html( get_theme_mod( 'rivross_real_estate_newsletter_description', __( 'Subscribe to get the best property deals and updates.', 'rivross-corporate' ) ) ); ?></p></div><?php echo rivross_newsletter_notice(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><form action="<?php echo esc_url( get_permalink() ); ?>" method="post"><?php echo rivross_newsletter_form_fields( 'property' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><input type="email" name="newsletter_email" placeholder="<?php esc_attr_e( 'Enter your email address', 'rivross-corporate' ); ?>" aria-label="<?php esc_attr_e( 'Email address', 'rivross-corporate' ); ?>" required><button class="rivross-button" type="submit"><?php esc_html_e( 'Subscribe', 'rivross-corporate' ); ?> <?php echo rivross_icon( 'arrow' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></button></form></div></section>
</div>
<?php get_footer(); ?>
