<?php
/** Single RIVROSS project page. */
get_header();
while ( have_posts() ) : the_post();
	$id = get_the_ID(); $image = rivross_project_image_url( $id ); $terms = get_the_terms( $id, 'rivross_project_type' ); $type = ! empty( $terms ) && ! is_wp_error( $terms ) ? $terms[0]->name : rivross_project_meta( $id, 'type', __( 'Project', 'rivross-corporate' ) ); $location = rivross_project_meta( $id, 'location' ); $map = rivross_project_meta( $id, 'map_url' ); $map = $map ? $map : 'https://www.google.com/maps/search/?api=1&query=' . rawurlencode( $location ); $inquiry = rivross_project_meta( $id, 'inquiry_url' ); $inquiry = $inquiry ? $inquiry : home_url( '/contact-us/#contact-form' ); $gallery = preg_split( '/\r?\n|,/', (string) rivross_project_meta( $id, 'gallery' ) ); $gallery = array_values( array_filter( array_map( 'trim', $gallery ) ) ); if ( empty( $gallery ) ) { $gallery = array( $image ); }
	$facts = array( array( 'building', __( 'Developer / Partner', 'rivross-corporate' ), rivross_project_meta( $id, 'developer' ) ), array( 'grid', __( 'Project Type', 'rivross-corporate' ), $type ), array( 'pin', __( 'Location', 'rivross-corporate' ), $location ), array( 'ruler', __( 'Size / Area', 'rivross-corporate' ), rivross_project_meta( $id, 'size' ) ), array( 'bed', __( 'Bedrooms / Space', 'rivross-corporate' ), rivross_project_meta( $id, 'bedrooms' ) ), array( 'car', __( 'Parking / Road', 'rivross-corporate' ), rivross_project_meta( $id, 'parking' ) ), array( 'shield', __( 'Status', 'rivross-corporate' ), rivross_project_meta( $id, 'status' ) ), array( 'money', __( 'Price', 'rivross-corporate' ), rivross_project_meta( $id, 'price' ) ), array( 'calendar', __( 'Timeline', 'rivross-corporate' ), rivross_project_meta( $id, 'timeline' ) ) );
?>
<section class="projects-hero projects-single-hero" style="--projects-hero-image:url('<?php echo esc_url( $image ); ?>');"><div class="rivross-container rivross-container--wide projects-hero__inner"><nav class="projects-hero__breadcrumb" aria-label="<?php esc_attr_e( 'Breadcrumb', 'rivross-corporate' ); ?>"><a href="<?php echo esc_url( home_url( '/' ) ); ?>"><?php esc_html_e( 'Home', 'rivross-corporate' ); ?></a><span>›</span><a href="<?php echo esc_url( home_url( '/projects/' ) ); ?>"><?php esc_html_e( 'Projects', 'rivross-corporate' ); ?></a><span>›</span><span><?php the_title(); ?></span></nav><div class="projects-hero__copy"><h1><span><?php echo esc_html( $type ); ?></span><strong><?php the_title(); ?></strong></h1><i></i><p><?php echo esc_html( wp_trim_words( get_the_excerpt(), 25, '…' ) ); ?></p></div></div></section>
<main class="projects-single-main"><div class="rivross-container rivross-container--wide"><div class="projects-single-grid"><div><figure class="projects-single-feature"><img src="<?php echo esc_url( $image ); ?>" alt="<?php echo esc_attr( get_the_title() ); ?>"></figure><h2 class="projects-single-title"><?php the_title(); ?></h2><p class="projects-single-location"><?php echo rivross_icon( 'pin' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><?php echo esc_html( $location ); ?></p><div class="projects-single-facts"><?php foreach ( $facts as $fact ) : ?><div><span><?php echo rivross_icon( $fact[0] ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></span><small><?php echo esc_html( $fact[1] ); ?></small><strong><?php echo esc_html( $fact[2] ); ?></strong></div><?php endforeach; ?></div><div class="projects-single-copy"><h2><?php esc_html_e( 'Project Overview', 'rivross-corporate' ); ?></h2><?php the_content(); ?></div><section class="projects-single-gallery"><h2><?php esc_html_e( 'Project Gallery', 'rivross-corporate' ); ?></h2><div><?php foreach ( $gallery as $gallery_image ) : ?><img src="<?php echo esc_url( $gallery_image ); ?>" alt="<?php echo esc_attr( get_the_title() ); ?>"><?php endforeach; ?></div></section></div><aside class="projects-single-aside"><h2><?php esc_html_e( 'Interested in this project?', 'rivross-corporate' ); ?></h2><p><?php esc_html_e( 'Talk with our team about availability, partnership and investment opportunities.', 'rivross-corporate' ); ?></p><a class="rivross-button" href="<?php echo esc_url( $inquiry ); ?>"><?php esc_html_e( 'Discuss This Project', 'rivross-corporate' ); ?> <?php echo rivross_icon( 'arrow' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></a><a class="rivross-button projects-single-aside__outline" href="<?php echo esc_url( $map ); ?>" target="_blank" rel="noopener"><?php esc_html_e( 'View Map Location', 'rivross-corporate' ); ?> <?php echo rivross_icon( 'map' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></a></aside></div></div></main>
<?php endwhile; get_footer(); ?>
